export interface FilmsInt {
    added: string;
    category_id: string;
    category_ids: number[];
    container_extension: string;
    custom_sid: null;
    direct_source: string;
    is_adult: number;
    name: string;
    num: number;
    rating: string;
    stream_icon: string;
    stream_id: number;
    stream_type: string;
    rating_5based: number;
    trailer: string;
}

export const dataFilms = [
    {
        num: 1,
        name: "Adventures in Public School",
        stream_type: "movie",
        stream_id: 164557,
        stream_icon:
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/m7prbaNnkmPlW3u87Yf8QYeJeNf.jpg",
        rating: "7.5",
        rating_5based: 3.8,
        tmdb: 471515,
        trailer: "",
        added: "1701276852",
        is_adult: 0,
        category_id: "108",
        category_ids: [108],
        container_extension: "mp4",
        custom_sid: null,
        direct_source: "",
    },
    {
        num: 2,
        name: "Knight and Day",
        stream_type: "movie",
        stream_id: 162337,
        stream_icon:
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/phhp52CZZJiGYmiOTp9ZBDkGHB3.jpg",
        rating: "5.2",
        rating_5based: 2.6,
        tmdb: 37834,
        trailer: "",
        added: "1701276762",
        is_adult: 0,
        category_id: "48",
        category_ids: [48],
        container_extension: "mp4",
        custom_sid: null,
        direct_source: "",
    },
    {
        num: 3,
        name: "Maz Jobrani: Immigrant",
        stream_type: "movie",
        stream_id: 161964,
        stream_icon:
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/eKjpRVYExmMhMtO0HTjSdSed5zy.jpg",
        rating: "6.7",
        rating_5based: 3.4,
        tmdb: 468366,
        trailer: "",
        added: "1701276747",
        is_adult: 0,
        category_id: "108",
        category_ids: [108],
        container_extension: "mp4",
        custom_sid: null,
        direct_source: "",
    },
    {
        num: 4,
        name: "The House",
        stream_type: "movie",
        stream_id: 160239,
        stream_icon:
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/iZjMFSKCrleKolC1gYcz5Rs8bk1.jpg",
        rating: "6.8",
        rating_5based: 3.4,
        tmdb: 926899,
        trailer: "",
        added: "1701276676",
        is_adult: 0,
        category_id: "49",
        category_ids: [49],
        container_extension: "mp4",
        custom_sid: null,
        direct_source: "",
    },
    {
        num: 5,
        name: "It",
        stream_type: "movie",
        stream_id: 162536,
        stream_icon:
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg",
        rating: "8.6",
        rating_5based: 4.3,
        tmdb: 346364,
        trailer: "",
        added: "1701276770",
        is_adult: 0,
        category_id: "45",
        category_ids: [45],
        container_extension: "mp4",
        custom_sid: null,
        direct_source: "",
    },
    {
        num: 6,
        name: "Florence Foster Jenkins",
        stream_type: "movie",
        stream_id: 163146,
        stream_icon:
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/1HAdtUchzWEo0LMFHrgD2UBIBS3.jpg",
        rating: "8.8",
        rating_5based: 4.4,
        tmdb: 315664,
        trailer: "",
        added: "1701276795",
        is_adult: 0,
        category_id: "108",
        category_ids: [108],
        container_extension: "mp4",
        custom_sid: null,
        direct_source: "",
    },
    {
        num: 7,
        name: "Kill the Messenger",
        stream_type: "movie",
        stream_id: 162374,
        stream_icon:
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/8gaNZiKZHvKCqMDByY00dUIV0YC.jpg",
        rating: "7.7",
        rating_5based: 3.9,
        tmdb: 245916,
        trailer: "",
        added: "1701276764",
        is_adult: 0,
        category_id: "56",
        category_ids: [56],
        container_extension: "mp4",
        custom_sid: null,
        direct_source: "",
    },
    {
        num: 8,
        name: "Let's Scare Julie",
        stream_type: "movie",
        stream_id: 162244,
        stream_icon:
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/1c7OsovY4s15sLp8AfzxR92fTCU.jpg",
        rating: "4.6",
        rating_5based: 2.3,
        tmdb: 537736,
        trailer: "",
        added: "1701276758",
        is_adult: 0,
        category_id: "45",
        category_ids: [45],
        container_extension: "mp4",
        custom_sid: null,
        direct_source: "",
    },
    {
        num: 9,
        name: "The General",
        stream_type: "movie",
        stream_id: 160319,
        stream_icon:
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/nIp4gIXogCjfB1QABNsWwa9gSca.jpg",
        rating: "9.2",
        rating_5based: 4.6,
        tmdb: 961,
        trailer: "",
        added: "1701276679",
        is_adult: 0,
        category_id: "108",
        category_ids: [108],
        container_extension: "mp4",
        custom_sid: null,
        direct_source: "",
    },
    {
        num: 10,
        name: "The King's Man",
        stream_type: "movie",
        stream_id: 160157,
        stream_icon:
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/2BRbPr0JmkEuUy6TZsN2AVcW8Wr.jpg",
        rating: "4",
        rating_5based: 2,
        tmdb: 476669,
        trailer: "",
        added: "1701276672",
        is_adult: 0,
        category_id: "48",
        category_ids: [48],
        container_extension: "mp4",
        custom_sid: null,
        direct_source: "",
    },
    {
        num: 11,
        name: "The King",
        stream_type: "movie",
        stream_id: 160158,
        stream_icon:
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/1UjAFYwbDsd6xBK7KloKzUrElSH.jpg",
        rating: "6.3",
        rating_5based: 3.2,
        tmdb: 560082,
        trailer: "",
        added: "1701276672",
        is_adult: 0,
        category_id: "56",
        category_ids: [56],
        container_extension: "mp4",
        custom_sid: null,
        direct_source: "",
    },
    {
        num: 12,
        name: "John Early: Now More Than Ever",
        stream_type: "movie",
        stream_id: 162477,
        stream_icon:
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/iKkB3KTCVj2GYcTP1VwSQ5A8htL.jpg",
        rating: "6.4",
        rating_5based: 3.2,
        tmdb: 1111585,
        trailer: "",
        added: "1701276768",
        is_adult: 0,
        category_id: "108",
        category_ids: [108],
        container_extension: "mp4",
        custom_sid: null,
        direct_source: "",
    },
    {
        num: 13,
        name: "Linoleum",
        stream_type: "movie",
        stream_id: 162201,
        stream_icon:
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/lAdPsBMnP5ctvKavQY9y8JazygK.jpg",
        rating: "8.1",
        rating_5based: 4.1,
        tmdb: 765904,
        trailer: "",
        added: "1701276756",
        is_adult: 0,
        category_id: "40",
        category_ids: [40],
        container_extension: "mp4",
        custom_sid: null,
        direct_source: "",
    },
    {
        num: 1,
        name: "Adventures in Public School",
        stream_type: "movie",
        stream_id: 164557,
        stream_icon:
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/m7prbaNnkmPlW3u87Yf8QYeJeNf.jpg",
        rating: "7.5",
        rating_5based: 3.8,
        tmdb: 471515,
        trailer: "",
        added: "1701276852",
        is_adult: 0,
        category_id: "108",
        category_ids: [108],
        container_extension: "mp4",
        custom_sid: null,
        direct_source: "",
    },
    {
        num: 1,
        name: "Adventures in Public School",
        stream_type: "movie",
        stream_id: 164557,
        stream_icon:
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/m7prbaNnkmPlW3u87Yf8QYeJeNf.jpg",
        rating: "7.5",
        rating_5based: 3.8,
        tmdb: 471515,
        trailer: "",
        added: "1701276852",
        is_adult: 0,
        category_id: "108",
        category_ids: [108],
        container_extension: "mp4",
        custom_sid: null,
        direct_source: "",
    },
    {
        num: 1,
        name: "Adventures in Public School",
        stream_type: "movie",
        stream_id: 164557,
        stream_icon:
            "https://image.tmdb.org/t/p/w600_and_h900_bestv2/m7prbaNnkmPlW3u87Yf8QYeJeNf.jpg",
        rating: "7.5",
        rating_5based: 3.8,
        tmdb: 471515,
        trailer: "",
        added: "1701276852",
        is_adult: 0,
        category_id: "108",
        category_ids: [108],
        container_extension: "mp4",
        custom_sid: null,
        direct_source: "",
    },
];
